spring:
  main:
    banner-mode: off
  h2.console:
    enabled: true
    path: /console
  datasource:
    url: 'jdbc:h2:file:C:/Users/konra/Desktop/Projekty/SpringBootNewbie/todo-app/todo-db'
task.allowMultipleTasksFromTemplate: false